"""Stage 38 Standard half: source/generated/artifact/cache/evidence/
protected plane enforcement.

Agents must edit the right representation: source is written by
hand, generated output is regenerated by its declared command,
artifacts are inventory-bound, caches are never committed,
evidence lives under .evidence/, and protected control-plane
paths need explicit authorization. ``classify`` maps one file
event to its plane finding; ``validate_plane_corpus`` checks
the frozen oracle. Findings are repair guidance (plane +
message + excerpt), never an error: ``FINDING_FIELDS`` names
the five required keys, ``SEVERITIES`` names the allowed
severities, and ``validate_finding`` returns repair strings
(empty means valid). Pure functions: no I/O, no subprocess, no
network — file events in, violations out. Pre-commit runs the
same classifier locally; the PR Gate runs ``verify --select``
on the same tree.
"""

from typing import Any, Dict, List, Optional, Tuple

import re as _re

# Frozen planes, in classifier precedence (protected first,
# source last as the default).
PLANES = ("source", "generated", "artifact", "cache", "evidence",
          "protected")

SEVERITIES = ("blocker", "major", "minor")

FINDING_FIELDS = ("id", "rule", "finding", "severity", "excerpt")

# Frozen violation rules, in check order.
RULES = (
    "generated-direct-edit",
    "generated-stale",
    "cache-committed",
    "evidence-misplaced",
    "protected-unauthorized",
    "orphan-directory",
    "stale-artifact",
)

GENERATED_PREFIXES = ("Canonical/generated/",)

ARTIFACT_PREFIXES = ("Canonical/schemas/", "Canonical/capabilities.json",
                     "Canonical/v4.2-preservation.csv")

CACHE_MARKERS = (".worktrees/", "__pycache__/", ".evidence/cache",
                 ".pyc", ".cache/")

EVIDENCE_PREFIXES = (".evidence/",)

PROTECTED_PATHS = (".github/workflows/pr-gate.yml",
                   ".github/workflows/merge-policy.yml")

# Entry-ID shape for the frozen oracle.
_ENTRY_ID_RE = _re.compile(r"^plane-enforcement\.[a-z-]+\.\d{2}$")


def _make_finding(rule: str, message: str, excerpt: str,
                  severity: str = "major") -> Dict[str, str]:
    """Build one structured plane finding dict."""
    return {
        "id": "%s-1" % rule,
        "rule": rule,
        "finding": message,
        "severity": severity,
        "excerpt": excerpt[:200],
    }


def validate_finding(finding: Any) -> List[str]:
    """Return repair strings for one finding; empty means valid."""
    if not isinstance(finding, dict):
        return ["finding must be a mapping of plain data, not %s"
                % type(finding).__name__]
    repairs = []
    for key in FINDING_FIELDS:
        if key not in finding:
            repairs.append("finding is missing required key %r" % key)
    rule = finding.get("rule")
    if "rule" in finding and rule not in RULES:
        repairs.append("finding rule %r is not a frozen Stage 38 "
                       "plane rule" % (rule,))
    if "severity" in finding and finding.get("severity") not in SEVERITIES:
        repairs.append("finding severity %r must be "
                       "blocker|major|minor" % (finding.get("severity"),))
    return repairs


def plane_for(path: str) -> str:
    """Classify one path to its plane (protected first, source
    default). Mirrors tools/repo_map.plane_for precedence so the
    classifier and the map never disagree."""
    text = str(path or "").replace("\\", "/").strip().lstrip("/")
    if not text:
        return "source"
    for guard in PROTECTED_PATHS:
        if text == guard or text.startswith(guard.rstrip("/") + "/"):
            return "protected"
    for prefix in EVIDENCE_PREFIXES:
        if text.startswith(prefix):
            return "evidence"
    for marker in CACHE_MARKERS:
        if marker in text:
            return "cache"
    for prefix in ARTIFACT_PREFIXES:
        if text.startswith(prefix):
            return "artifact"
    for prefix in GENERATED_PREFIXES:
        if text.startswith(prefix):
            return "generated"
    return "source"


def _excerpt(event: Dict[str, Any]) -> str:
    """Short evidence excerpt naming the path."""
    path = event.get("path")
    if isinstance(path, (str, int, float)) and str(path).strip():
        return str(path)[:200]
    return "(event)"


def _normalize_event(event: Any) -> Dict[str, Any]:
    """Fill total defaults so partial input never crashes."""
    event = event if isinstance(event, dict) else {}
    return {
        "path": str(event.get("path", "")),
        "edited": bool(event.get("edited", False)),
        "regenerated": bool(event.get("regenerated", False)),
        "declared_migration": bool(event.get(
            "declared_migration", False)),
        "source_changed": bool(event.get(
            "source_changed", False)),
        "stale": bool(event.get("stale", False)),
        "deleted_source": bool(event.get(
            "deleted_source", False)),
        "authorized": bool(event.get("authorized", False)),
        "is_dir": bool(event.get("is_dir", False)),
        "has_owner": bool(event.get("has_owner", True)),
    }


def _check_generated(event: Dict[str, Any],
                     plane: str) -> List[Dict[str, str]]:
    """Generated plane: direct edits refused; declared migrations
    pass; stale output after a source change fails."""
    if plane != "generated":
        return []
    if event["edited"] and not event["regenerated"]:
        if event["declared_migration"]:
            return []
        return [_make_finding(
            "generated-direct-edit",
            "direct edit of generated file %r refused: regenerate "
            "via the owning tool instead" % event["path"],
            _excerpt(event))]
    if event["source_changed"] and event["stale"]:
        return [_make_finding(
            "generated-stale",
            "stale generated file %r after its source changed: "
            "regenerate before merging" % event["path"],
            _excerpt(event))]
    return []


def _check_cache(event: Dict[str, Any],
                 plane: str) -> List[Dict[str, str]]:
    """Cache plane: caches are never committed."""
    if plane == "cache" and event["edited"]:
        return [_make_finding(
            "cache-committed",
            "cache path %r must never be committed: keep caches "
            "untracked" % event["path"],
            _excerpt(event))]
    return []


def _check_evidence(event: Dict[str, Any],
                    plane: str) -> List[Dict[str, str]]:
    """Evidence plane: evidence lives under .evidence/; source
    trees never hold evidence files."""
    path = event["path"].replace("\\", "/").lstrip("/")
    if plane != "evidence" and event["edited"]:
        lower = path.lower()
        if lower.endswith(".evidence.json") or "/evidence/" in lower:
            return [_make_finding(
                "evidence-misplaced",
                "evidence file %r placed in source: move it under "
                ".evidence/" % event["path"],
                _excerpt(event))]
    return []


def _check_protected(event: Dict[str, Any],
                     plane: str) -> List[Dict[str, str]]:
    """Protected plane: control-plane edits need authorization."""
    if plane == "protected" and event["edited"] \
            and not event["authorized"]:
        return [_make_finding(
            "protected-unauthorized",
            "protected path %r edited without authorization: "
            "record owner authorization first" % event["path"],
            _excerpt(event), severity="blocker")]
    return []


def _check_orphan(event: Dict[str, Any],
                  plane: str) -> List[Dict[str, str]]:
    """Source plane: new directories need a current owner."""
    if event["is_dir"] and not event["has_owner"]:
        return [_make_finding(
            "orphan-directory",
            "new directory %r has no current responsibility or "
            "ownership: create it with its owner, not for future "
            "organization" % event["path"],
            _excerpt(event))]
    return []


def _check_stale_artifact(event: Dict[str, Any],
                          plane: str) -> List[Dict[str, str]]:
    """Artifact plane: a deleted source must not leave a stale
    artifact behind."""
    if plane == "artifact" and event["deleted_source"]:
        return [_make_finding(
            "stale-artifact",
            "deleted source left stale artifact %r: remove or "
            "regenerate the artifact with its source" % event["path"],
            _excerpt(event))]
    return []


_CHECKS = (
    _check_generated,
    _check_cache,
    _check_evidence,
    _check_protected,
    _check_orphan,
    _check_stale_artifact,
)


class PlaneResult:
    """One plane classification outcome for one file event."""

    clean: bool = False
    findings: List[Dict[str, str]] = []  # type: ignore[assignment]

    def __init__(self, clean: bool = False,
                 findings: Optional[List[Dict[str, str]]] = None):
        self.clean = clean
        self.findings = list(findings or [])


def classify(event: Any) -> PlaneResult:
    """Map one file event to its plane findings.

    The path's plane decides which checks run; any finding means
    the event is not clean. A fully clean event returns
    ``clean=True`` with zero findings. Pure function: no I/O,
    deterministic in its input. This classifies; it never edits,
    never regenerates, never authorizes.
    """
    normalized = _normalize_event(event)
    plane = plane_for(normalized["path"])
    findings: List[Dict[str, str]] = []
    for check in _CHECKS:
        findings.extend(check(normalized, plane))
    if findings:
        return PlaneResult(clean=False, findings=findings)
    return PlaneResult(clean=True, findings=[])


def clean_event() -> Dict[str, Any]:
    """One clean file event (CLEAN with zero findings).

    A hand-written source edit with no plane complications.
    Callers mutate one dimension per test.
    """
    return {
        "path": "tools/plane_enforcement.py",
        "edited": True,
        "regenerated": False,
        "declared_migration": False,
        "source_changed": False,
        "stale": False,
        "deleted_source": False,
        "authorized": False,
        "is_dir": False,
        "has_owner": True,
    }


def _entries_of(corpus: Any) -> List[Dict[str, Any]]:
    if isinstance(corpus, dict):
        entries = corpus.get("entries")
    else:
        entries = corpus
    if not isinstance(entries, list):
        return []
    return entries


def validate_plane_corpus(corpus: Any) -> Tuple[List[str],
                                                List[Dict[str, Any]]]:
    """Validate the frozen plane fixture oracle.

    Returns (findings, entries); an empty findings list means
    the corpus is a valid frozen oracle: frozen marker set,
    stable provenance, at least 8 entries, unique well-formed
    IDs, every entry computing its expected rules and clean
    flag, and all 7 plane rules covered.
    """
    if isinstance(corpus, dict):
        if corpus.get("_frozen") is not True:
            return (["plane corpus is not frozen: set "
                     "\"_frozen\": true"], [])
        provenance = str(corpus.get("_provenance", ""))
        if "Stage 38 #129" not in provenance:
            return (["plane corpus provenance must name "
                      "\"Stage 38 #129\""], [])
    elif not isinstance(corpus, list):
        return (["plane corpus must be a JSON object with an "
                 "'entries' array (or a bare array)"], [])
    entries = _entries_of(corpus)
    findings: List[str] = []
    if len(entries) < 8:
        findings.append("plane corpus holds %d entries, want "
                        "at least 8" % len(entries))
    seen: Dict[str, int] = {}
    covered = set()
    for index, entry in enumerate(entries):
        if not isinstance(entry, dict):
            findings.append("entries[%d] is not a mapping" % index)
            continue
        cid = str(entry.get("id", ""))
        if not _ENTRY_ID_RE.match(cid):
            findings.append("entry %r: id is not "
                            "plane-enforcement.<class>.<nn>" % cid)
        if cid in seen:
            findings.append("duplicate entry id %s (entries %d "
                            "and %d)" % (cid, seen[cid], index))
        else:
            seen[cid] = index
        if not str(entry.get("note", "")).strip():
            findings.append("entry %s: a one-line adjudication note "
                            "is required" % cid)
        expected = entry.get("expected_rules")
        if not isinstance(expected, list):
            findings.append("entry %s: expected_rules must be a list"
                            % cid)
            continue
        for rule in expected:
            if rule not in RULES:
                findings.append("entry %s: unknown expected rule %r"
                                % (cid, rule))
        covered.update(str(r) for r in expected
                       if isinstance(r, str))
        if "expected_clean" not in entry:
            findings.append("entry %s: expected_clean is required"
                            % cid)
        result = classify(entry.get("event", {}))
        computed = sorted({f["rule"] for f in result.findings})
        if sorted(str(r) for r in expected) != computed:
            findings.append("entry %s: expected_rules %r != "
                            "classify %r"
                            % (cid, sorted(str(r)
                                           for r in expected),
                               computed))
        if bool(entry.get("expected_clean")) != result.clean:
            findings.append("entry %s: expected_clean %r != "
                            "classify %r" % (cid, entry.get(
                                "expected_clean"),
                                result.clean))
    for rule in RULES:
        if rule not in covered:
            findings.append("rule %r has no entries (all 7 "
                            "plane rules are required)"
                            % rule)
    return findings, entries
